In [3]:
import numpy as np

In [4]:
#list
arr = [[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [5]:
#make it array
np.array(arr)

array([[1, 2],
       [3, 4]])

In [6]:
import torch

In [8]:
#make it to pytorch tensor
torch.Tensor(arr)

tensor([[ 1.,  2.],
        [ 3.,  4.]])

### 1.2 create matrix

In [9]:
np.ones([2,2])

array([[ 1.,  1.],
       [ 1.,  1.]])

In [10]:
torch.ones(2,2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [11]:
np.random.rand(2,2)

array([[ 0.40931484,  0.84106881],
       [ 0.05603079,  0.21521943]])

In [12]:
torch.rand(2,2)

tensor([[ 0.4913,  0.8315],
        [ 0.7052,  0.0229]])

### 1.3 Seed reproductivity

In [24]:
np.random.seed(0)#as one seed
np.random.rand(2,2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [25]:
np.random.rand(2,2)

array([[ 0.4236548 ,  0.64589411],
       [ 0.43758721,  0.891773  ]])

In [26]:
np.random.seed(0)
np.random.rand(2,2)#now same again

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [27]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

In [28]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

In [32]:
torch.rand(2,2)#different everytime

tensor([[ 0.6977,  0.8000],
        [ 0.1610,  0.2823]])

### Seed for GPU is different for now

In [34]:
#if you use gpu, use this code instead
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

### Numpy to torch

In [36]:
np_array = np.ones((2,2))

In [37]:
print(np_array)

[[ 1.  1.]
 [ 1.  1.]]


In [38]:
print(type(np_array))

<class 'numpy.ndarray'>


In [39]:
torch_tensor = torch.from_numpy(np_array)

In [40]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [43]:
np_array_new = np.ones((2,2),dtype = np.int8)
np_array_new

array([[1, 1],
       [1, 1]], dtype=int8)

In [45]:
torch.from_numpy(np_array_new)
# only support: double, float, float16, int64, int32, and uint8.

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

In [46]:
#data types matter

In [56]:
np_array_new = np.ones((2,2),dtype = np.float64)
torch.from_numpy(np_array_new)

tensor([[ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float64)

In [58]:
np_array_new = np.ones((2,2),dtype = np.int32)
torch.from_numpy(np_array_new)

tensor([[ 1,  1],
        [ 1,  1]], dtype=torch.int32)

In [59]:
np_array_new = np.ones((2,2),dtype = np.float16)
torch.from_numpy(np_array_new)

tensor([[ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float16)

In [52]:
np_array_new = np.ones((2,2),dtype = np.double)
torch.from_numpy(np_array_new)

tensor([[ 1.,  1.],
        [ 1.,  1.]], dtype=torch.float64)

In [60]:
#be aware of all the numpy and tensor match up when calculations

In [61]:
torch_tensor = torch.ones(2,2)

In [62]:
type(torch_tensor)

torch.Tensor

In [64]:
torch_to_numpy = torch_tensor.numpy()#this make torch tensor numpy
torch_to_numpy

array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

In [65]:
type(torch_to_numpy)

numpy.ndarray

### 1.4 Tensors on CPU and GPU

In [67]:
#CPU
tensor_cpu = torch.ones(2,2)

In [69]:
#move tensors from cpu to gpu
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [70]:
#GPU to cpu
tensor_cpu.cpu()

tensor([[ 1.,  1.],
        [ 1.,  1.]])

### 1.5 Tensor Operations
### Resizing Tensor

In [86]:
a = torch.ones(2,2)
a

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [87]:
print(a.size())

torch.Size([2, 2])


In [88]:
a.view(4)

tensor([ 1.,  1.,  1.,  1.])

In [89]:
a.view(4).size()

torch.Size([4])

### Element-wise Addition

In [90]:
a = torch.ones(2,2)
a

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [91]:
b = torch.ones(2,2)
b

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [92]:
c= a+b
c

tensor([[ 2.,  2.],
        [ 2.,  2.]])

In [93]:
d = torch.add(a,b)#same as above
print(d)

tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [94]:
print('old c tensor')
print(c)

c.add_(a)#elegant way to do the adding#add a to c and replace it

print('new c tensor')
print(c)

old c tensor
tensor([[ 2.,  2.],
        [ 2.,  2.]])
new c tensor
tensor([[ 3.,  3.],
        [ 3.,  3.]])


### Subtraction

In [95]:
print(a)
print(b)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [96]:
a - b

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [97]:
print(a.sub(b))

tensor([[ 0.,  0.],
        [ 0.,  0.]])


In [99]:
print(a)#did not change

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [100]:
print(a.sub_(b))#add"_"will make it update

tensor([[ 0.,  0.],
        [ 0.,  0.]])


In [101]:
print(a)

tensor([[ 0.,  0.],
        [ 0.,  0.]])


### Element wise Multiplication

In [110]:
a = torch.ones(2,2)
print(a)
b = torch.zeros(2,2)
print(b)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 0.,  0.],
        [ 0.,  0.]])


In [111]:
a * b

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [112]:
print(torch.mul(a,b))
print(a)

tensor([[ 0.,  0.],
        [ 0.,  0.]])
tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [114]:
print(a.mul_(b))

tensor([[ 0.,  0.],
        [ 0.,  0.]])


In [115]:
print(a)

tensor([[ 0.,  0.],
        [ 0.,  0.]])


### Division

In [116]:
a = torch.ones(2,2)
print(a)
b = torch.zeros(2,2)
print(b)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 0.,  0.],
        [ 0.,  0.]])


In [117]:
print(b/a)

tensor([[ 0.,  0.],
        [ 0.,  0.]])


In [120]:
b.div_(a)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [121]:
print(b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])


### Tensor Mean

In [122]:
a =  torch.Tensor([1,2,3,4,5,6,7,8])

In [123]:
a.mean(dim=0)

tensor(4.5000)

In [124]:
a.mean(dim=1)#will error

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [126]:
b =  torch.Tensor([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])

In [127]:
b.size()

torch.Size([2, 8])

In [128]:
b.mean(dim=1)

tensor([ 4.5000,  4.5000])

### Standard Deviation

In [129]:
a =  torch.Tensor([1,2,3,4,5,6,7,8])
a.std(dim = 0)

tensor(2.4495)